master-key: ENC[AES256_GCM,data:ke3UsEsI+aqgRSeEyqsYTP+OIFnZfBNYM85BG91sKhKsxHRueJGZQQZTdsE2kqf09Gbpu37X9qNlt6dnzwbO7Q==,iv:f7fWDmXopgoWOhoLZ30bLB2NOz4lZE3qMJ+y6fYiKjU=,tag:bh5kcGFxg0udNCfXl61VrA==,type:str]
openrouter-api-key: ENC[AES256_GCM,data:nB6Hqf8hFmODP5kyDkF46NJoAMkwh6iux/85Ki/DzVixg9fy8rF4fgcmQsOB8XQWw9nuCDhVR0hedlB/UM7TROr7eXOgS7iEIg==,iv:OnD/MCnBYO5bMWDSZdSINBinX6Vny5bV1MJZuLims4Q=,tag:n2G15Wt5yv0/OW+pdwjGRw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPaXUwejNJM2JqSGc3eG9o
            SDRoL0xpZEpFY0RJZTIzTS9BczB2MlBaZTAwClFnRGFTMkxXMVNHaXIwS2d3dlk4
            czJwbDVWbWp2TW9HMmRpcHZIaTFndk0KLS0tIExJUWM1ejgrSllWTkMvNGpndHJL
            NFlQNWs0WEl2bzF0MCtONFlEem1BOTQKgkOxqg9P/24XM81hWrHme4ltVRensSb6
            x+MHcd8Ts4FJ/eBK7slLFENWwCiIRbTITDp2Ri9Mx2SuJKTuILjvJg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vjhlz2h8j5wm8jjfjtg785rzg02yxaj8fx565d67m565qw8uygusadh7nh
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTWRyc1M5NHpDNmpZOHVu
            Ris5ZHZRNFJqMXExMElHSXlCcFVMRmVwVFdZCnB2YWlKdTBHeWxpeHkvczRvMUd0
            ZGVxVHB4clhtVE4wNld6NzBDYUNGcEEKLS0tIGRjUzJ1U1pDLzJxdUI5MDZKRVhh
            bTRrQXQvTkY4RWNlVUJMN0dHaDhKZVEK33OlPzYTtYFKcLE2wMTSqj8D1MU0PY+G
            1g3CnLkH+8/hQxAnLqvFMUFTpaELzEV5se0UWFvWsqO6OWR3RHk0rA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yzy89s2w7ns80xkr9sgtank0e27d37lrvk5vx8ck9sccja0ckpdsasy6e9
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2TXJ2SThkMjdBME93Y3d0
            OG1DVXB1MnB4TXJnTEdJbTUwVTFBODkzY0dRCjZvZFdqcXhwZXhWUy83M0NzdlZn
            bkRBLzdYSE9ENWFlK3JZek9nUnBGZkUKLS0tIG1OQTNnc0ZUOGlMNm43Sjg1elBS
            L3djQ29xcENUTy9idXZRMnplcjdCMDgKtuyIsozccAhWiYii4psABoXzz42qLCL1
            HeWMTw9kZMVY2xTh4/OrxHJs76KBGiE0STteBu7Oi2YP0254qme5Gw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age105ez8g35zt5en5n37cy0dzug77dwjwcxnal6jlcve30psdnh8euq82hyew
    lastmodified: "2026-08-12T22:38:38Z"
    mac: ENC[AES256_GCM,data:/uHG7zl8ApRbAjqF7OX/Et9VPGVm3qYpU7aF6QUZ+ZmBnvXOVRZBsAZc7Q8WFLDcOsIpmqsY4lKJ7FL0jl0M4YQRqFuu6VB4caimL29qRXbkhX3U/UgvVyuS6i6fPV7qbw6oVe3t55O0E29igEsK3/V5k6KRkRGCY0CuMVgDbe8=,iv:EAd23IIuDjV695IeIVPNQkJPx8qMOv209zGwej69SzI=,tag:gnQ2nPOYH2BRH6TT9IHerA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
