master-key: ENC[AES256_GCM,data:ke3UsEsI+aqgRSeEyqsYTP+OIFnZfBNYM85BG91sKhKsxHRueJGZQQZTdsE2kqf09Gbpu37X9qNlt6dnzwbO7Q==,iv:f7fWDmXopgoWOhoLZ30bLB2NOz4lZE3qMJ+y6fYiKjU=,tag:bh5kcGFxg0udNCfXl61VrA==,type:str]
openrouter-api-key: ENC[AES256_GCM,data:IJAGZXFcWniatGlZeDsYUkeemf85bohgjg0uQRHzQRiEC9MeSqj7gqmXn6vtYeEY8O/SEQhD5nLUyRYbXLDjY72WdlXDD8w/JA==,iv:1XmIkCqg4xlPYK4E6FPoTcmQds0BH2f3/5R8QvTiIWQ=,tag:PK/hwwiRyF9RymfhYIkmfA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVT0NrNlBlN09vTFZ2MHA3
            UmIvTGcrUDVLU2dlUEY4SEVIcjhPSWJaVEVNClNnYmdGSFRuU2xwcTg4cXRMVXpv
            a1hJVE43RENGTzIwdTlXL0llMjdZY3MKLS0tIDlsdjZKWDJxTFErQVNpdVFWanpz
            c0owQk1STVVTNi9NTjAzZ0kxTGhNYlkKmveF6qo6BSMUE1GFhaVBmrUNSSTm5o2D
            dj1E1k3OOzroor0/bW5x1DVdg+3vIEVvGa01DtdVK/uEXdjZIgKM5A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vjhlz2h8j5wm8jjfjtg785rzg02yxaj8fx565d67m565qw8uygusadh7nh
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZ1NlaVM1N20xK3JkRXRC
            UVdZaHBUdTVLUENEU0Q0NURtamo0elp3N2hZClZLcEQwazZNaURwSVREQmxSdHJV
            bUVXMVdMcnRwdlJHekVpa1hiL01xc0UKLS0tIElVakdjUkhIR0E4YkhqNUM4WW5K
            SDBpTXZQVWN4ZTdBSS9IYUk4Sk44UXcKEDoba3GEncbDf3soLsL/X48FzAHUovDT
            v3cwwEpzklUAS/BxMVnBrXPmlx8qdvGaOYnmoceTUV/Je080oH6OUQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yzy89s2w7ns80xkr9sgtank0e27d37lrvk5vx8ck9sccja0ckpdsasy6e9
    lastmodified: "2026-08-06T17:42:29Z"
    mac: ENC[AES256_GCM,data:9hfcHcJJUFZsE67+L+jouXdOX0PFK6/YThWej5t+bjU/p4/4O8VTlMcnjdZzaGck4cW0IlQNVy2bihQPDI55jbaPfx3Ymy1RIgsS+3z0ftzJR67ufFFiw1v0slPcvZIp1ClKI7QtXz2RTLvfviqP08h1/R8Z8Mm0hgmz4F6ufS8=,iv:KvMG0O+BDTSowMabBTPCxXjHal2AlxE8wQm3e84XwNs=,tag:+7ZH2ahHDLnCZ14wmuJK8g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
